apiVersion: v1
kind: replicaSet  
metadata: 
  name: replica-set
  labels:
    app: replica-set
spec:
  replicas: 3
  selector:
    matchLabels:
      app: replica-set
  template:
    metadata:
      labels:
        app: replica-set
  containers: 
  - name: app1
    image: supergiantkir/animals:bear
    ports: 
    - containerPort: 80
    volumeMounts:
    - mountPath: /storage/app1
      name: app-storage
  - name: app2
    image: yanivomc/spring-music:latest
    ports: 
    - containerPort: 3000
   volumeMounts:
   - mountPath: /storage/app2
     name: app-storage
 volumes:
   - name: app-storage
     hostPath:
       path: /tmp/files
       type: DirectoryOrCreate
