apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata: 
 name: nginx  
spec:
 containers: 
 - name: bear
   image: supergiantkir/animals:bear
   ports: 
   - containerPort: 80
 - name: nginx
   image: yanivomc/spring-music:latest
   ports: 
   - containerPort: 80
